<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_Important mainly because you often read</name>
   <tag></tag>
   <elementGuidId>7f23e00d-dd88-4884-90b8-71c7b93583a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id=':2m']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;:2m&quot;)[count(. | //tr[@id = ':2m' and (text() = 'Important mainly because you often read messages with this label.Click to teach Gmail this conversation is not important.unread, devteam 3, Undangan bergabung ke KODE dari PT PALUGADA, 10:53 AM, Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga.devteam 3Undangan bergabung ke KODE dari PT PALUGADA - Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga 10:53 AM' or . = 'Important mainly because you often read messages with this label.Click to teach Gmail this conversation is not important.unread, devteam 3, Undangan bergabung ke KODE dari PT PALUGADA, 10:53 AM, Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga.devteam 3Undangan bergabung ke KODE dari PT PALUGADA - Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga 10:53 AM')]) = count(//tr[@id = ':2m' and (text() = 'Important mainly because you often read messages with this label.Click to teach Gmail this conversation is not important.unread, devteam 3, Undangan bergabung ke KODE dari PT PALUGADA, 10:53 AM, Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga.devteam 3Undangan bergabung ke KODE dari PT PALUGADA - Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga 10:53 AM' or . = 'Important mainly because you often read messages with this label.Click to teach Gmail this conversation is not important.unread, devteam 3, Undangan bergabung ke KODE dari PT PALUGADA, 10:53 AM, Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga.devteam 3Undangan bergabung ke KODE dari PT PALUGADA - Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga 10:53 AM')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zA zE aqw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>ZdOxDb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>Tnvr6c:RNc9jf;PG1zDd:eyrEaf;WGbBt:UL4Ddb;nVvxM:UL4Ddb;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>nXDxbd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:2m</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:2n</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Important mainly because you often read messages with this label.Click to teach Gmail this conversation is not important.unread, devteam 3, Undangan bergabung ke KODE dari PT PALUGADA, 10:53 AM, Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga.devteam 3Undangan bergabung ke KODE dari PT PALUGADA - Hi, Selamat Datang di KODE! Email Anda kodetesting06@gmail.com telah di undang untuk bergabung di perusahaan PT PALUGADA. Silahkan signup atau login untuk menga 10:53 AM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:2m&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//tr[@id=':2m']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id=':2l']/tbody/tr</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Woohoo! You', &quot;'&quot;, 've read all the important messages in your inbox.')])[1]/following::tr[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr</value>
   </webElementXpaths>
</WebElementEntity>
