<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_supportkodeid</name>
   <tag></tag>
   <elementGuidId>54de36d1-30ce-47df-912a-b2ffbc1bfc59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='57fc5186-ff01-c7aa-5786-0a43e2b2347a']/div/div/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>support@kode.id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>support@kode.id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;57fc5186-ff01-c7aa-5786-0a43e2b2347a&quot;)/div[1]/div[@class=&quot;_1yIHkYLrqDZpAMQ3L2YILh _1E-ojjaYGhOxCgHp9Pe315 _1zRzYBa3Ymm8oRb7igyJMT _2-6Yr-35EHcBYQQ-DulaxW _2Ht9U0YzzfQGXALqVdO2MN WHHpfJX04sHbd6jCFcPxS&quot;]/div[@class=&quot;_1hHMVrN7VV4d6Ylz-FsMuP _18LAllQi61d4a4XNAr9prg&quot;]/div[@class=&quot;_2miAFnGHXlWwulyUmLEbzZ&quot;]/div[@class=&quot;l9wTN_3i3tZgMhfxzv1F6&quot;]/div[@class=&quot;_3zJzxRam-s-FYVZNqcZ0BW&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='57fc5186-ff01-c7aa-5786-0a43e2b2347a']/div/div/div/div[2]/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top results'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat datang di KODE, semua bisa belajar!'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
