<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verifikasi Email</name>
   <tag></tag>
   <elementGuidId>9848a093-a25f-415f-bc45-6df5f81c7812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[3]/div[2]/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/table/tbody/tr/td/div/table/tbody/tr[2]/td/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ptolemy.kode.id/verify-email?clientId=43pnru5cbe0gs4a2aas603fhpc&amp;userName=kodetesting01hotmailcom&amp;code=851040&amp;region=ap-southeast-1&amp;email=kodetesting01@hotmail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>NotApplicable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi
 Email </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;ms-Fabric _2HTFmaDIVHVbnIkwPM9srx root-40&quot;]/div[@class=&quot;_3KAPMPOz8KsW24ooeUflK2&quot;]/div[@class=&quot;_2jR8Yc0t2ByBbcz_HIGqZ4&quot;]/div[@class=&quot;_1TpU2KF6f_EeQiytBaYj8I&quot;]/div[@class=&quot;_3mBjlqTqXMUiRuuWRKCPtX css-39&quot;]/div[@class=&quot;_1jw6v9zFEgnOiXShpU1qqM&quot;]/div[@class=&quot;_2a8RUrS_Rz9TgOuFOyVU2E _1o7uVfs1ooIN78PbtKWnd1 _2Vkn_hMDpPrPod82gSw_7g&quot;]/div[@class=&quot;mm4nCLKbIRtx5HvuorDWT&quot;]/div[@class=&quot;_1QDTZfBsizkS8O4Jej5a3A&quot;]/div[1]/div[@class=&quot;_3Ad19uWCrJfZmaKfs-hR2p&quot;]/div[@class=&quot;_1fmZ_av0AzpX0WDUx7Rxsi&quot;]/div[@class=&quot;_2BDBxo-9kfOUcm02zcT5PR&quot;]/div[@class=&quot;aKEZUGyWi5haT6riFXgvp customScrollBar&quot;]/div[@class=&quot;_2le66D_cFAbkq67CrgZcmE&quot;]/div[@class=&quot;item-part&quot;]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;expanded-itempart B1IVVpQay0rPzznhParFr KcNy0Xfd9-is-_CEp3QOI&quot;]/div[2]/div[@class=&quot;_3U2q6dcdZCrTrR_42Nxby JWNdg1hee9_Rz6bIGvG1c allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_2523&quot;]/div[1]/div[1]/div[@class=&quot;x_shadow x_white&quot;]/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;x_mj-column-per-100 x_outlook-group-fix&quot;]/table[1]/tbody[1]/tr[2]/td[@class=&quot;x_btn-primary-red&quot;]/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[3]/div[2]/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/table/tbody/tr/td/div/table/tbody/tr[2]/td/table/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verifikasi
 Email')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KODE'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abaikan E-mail ini jika kamu merasa tidak pernah mendaftarkan diri untuk membuat akun di KODE.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan Penggunaan'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ptolemy.kode.id/verify-email?clientId=43pnru5cbe0gs4a2aas603fhpc&amp;userName=kodetesting01hotmailcom&amp;code=851040&amp;region=ap-southeast-1&amp;email=kodetesting01@hotmail.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
   </webElementXpaths>
</WebElementEntity>
