<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai</name>
   <tag></tag>
   <elementGuidId>d432728c-de08-4c1f-8d1e-955e1502fedb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Mulai' or . = 'Mulai')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yiv4475401539']/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yiv4475401539btn yiv4475401539btn-small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDVAeWFob28uY29tIiwiaWF0IjoxNTY5OTIyMzA5LCJleHAiOjE1Njk5MjI0ODl9.EZdUP6fXmoZV2Q7AFD0QIye0nnWLDy_KFDEDSLKQ7Kw&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting05@yahoo.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yiv4475401539&quot;)/div[1]/table[@class=&quot;yiv4475401539body yiv4475401539pb3&quot;]/tbody[1]/tr[1]/td[@class=&quot;yiv4475401539container&quot;]/table[2]/tbody[1]/tr[3]/td[@class=&quot;yiv4475401539text-center yiv4475401539pt2 yiv4475401539pb1&quot;]/a[@class=&quot;yiv4475401539btn yiv4475401539btn-small&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yiv4475401539']/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mulai')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kodetesting05@yahoo.com'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kepada:'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Hacktivate Teknologi Indonesia. All Rights Reserved.'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balas'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDVAeWFob28uY29tIiwiaWF0IjoxNTY5OTIyMzA5LCJleHAiOjE1Njk5MjI0ODl9.EZdUP6fXmoZV2Q7AFD0QIye0nnWLDy_KFDEDSLKQ7Kw&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting05@yahoo.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
   </webElementXpaths>
</WebElementEntity>
