<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai</name>
   <tag></tag>
   <elementGuidId>b9c2a384-9535-46d5-94f6-7c0a431d820f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDVAeWFob28uY29tIiwiaWF0IjoxNTY5OTI2OTA3LCJleHAiOjE1Njk5MjcwODd9.Rk-pYI-P4MlmTh4OIyIuNQsQCvJKXgkFmV9slPAItyo&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting05@yahoo.com' and (text() = 'Mulai' or . = 'Mulai')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yiv5958388696']/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yiv5958388696btn yiv5958388696btn-small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDVAeWFob28uY29tIiwiaWF0IjoxNTY5OTI2OTA3LCJleHAiOjE1Njk5MjcwODd9.Rk-pYI-P4MlmTh4OIyIuNQsQCvJKXgkFmV9slPAItyo&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting05@yahoo.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yiv5958388696&quot;)/div[1]/table[@class=&quot;yiv5958388696body yiv5958388696pb3&quot;]/tbody[1]/tr[1]/td[@class=&quot;yiv5958388696container&quot;]/table[2]/tbody[1]/tr[3]/td[@class=&quot;yiv5958388696text-center yiv5958388696pt2 yiv5958388696pb1&quot;]/a[@class=&quot;yiv5958388696btn yiv5958388696btn-small&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yiv5958388696']/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mulai')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kodetesting05@yahoo.com'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kepada:'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Hacktivate Teknologi Indonesia. All Rights Reserved.'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balas'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDVAeWFob28uY29tIiwiaWF0IjoxNTY5OTI2OTA3LCJleHAiOjE1Njk5MjcwODd9.Rk-pYI-P4MlmTh4OIyIuNQsQCvJKXgkFmV9slPAItyo&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting05@yahoo.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
   </webElementXpaths>
</WebElementEntity>
