<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai</name>
   <tag></tag>
   <elementGuidId>b88173b7-e3c6-4b6f-9ba8-f79941bfd185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[3]/div[2]/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'x_btn x_btn-small' and (text() = 'Mulai' or . = 'Mulai')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDNAb3V0bG9vay5jb20iLCJpYXQiOjE1Njk1NjY5MTQsImV4cCI6MTU3MjE1ODkxNH0.V2TQFve5styB92OPXuFlRJov0IH1ED-O5Z2NOvqPj68&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting03@outlook.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>NotApplicable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x_btn x_btn-small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ogsb</name>
      <type>Main</type>
      <value>rgb(230, 88, 86)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;ms-Fabric _2HTFmaDIVHVbnIkwPM9srx root-40&quot;]/div[@class=&quot;_3KAPMPOz8KsW24ooeUflK2&quot;]/div[@class=&quot;_2jR8Yc0t2ByBbcz_HIGqZ4&quot;]/div[@class=&quot;_1TpU2KF6f_EeQiytBaYj8I&quot;]/div[@class=&quot;_3mBjlqTqXMUiRuuWRKCPtX css-39&quot;]/div[@class=&quot;_1jw6v9zFEgnOiXShpU1qqM&quot;]/div[@class=&quot;_2a8RUrS_Rz9TgOuFOyVU2E _1o7uVfs1ooIN78PbtKWnd1 _2Vkn_hMDpPrPod82gSw_7g&quot;]/div[@class=&quot;mm4nCLKbIRtx5HvuorDWT&quot;]/div[@class=&quot;_1QDTZfBsizkS8O4Jej5a3A&quot;]/div[1]/div[@class=&quot;_3Ad19uWCrJfZmaKfs-hR2p&quot;]/div[@class=&quot;_1fmZ_av0AzpX0WDUx7Rxsi&quot;]/div[@class=&quot;_2BDBxo-9kfOUcm02zcT5PR&quot;]/div[@class=&quot;aKEZUGyWi5haT6riFXgvp customScrollBar&quot;]/div[@class=&quot;_2le66D_cFAbkq67CrgZcmE&quot;]/div[@class=&quot;item-part&quot;]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;expanded-itempart B1IVVpQay0rPzznhParFr KcNy0Xfd9-is-_CEp3QOI&quot;]/div[2]/div[@class=&quot;_3U2q6dcdZCrTrR_42Nxby JWNdg1hee9_Rz6bIGvG1c allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_d8a4&quot;]/div[1]/div[@class=&quot;_2Ypz6DjF0cnPXsnj_7roel&quot;]/table[@class=&quot;x_body x_pb3&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_container&quot;]/table[2]/tbody[1]/tr[3]/td[@class=&quot;x_text-center x_pt2 x_pb1&quot;]/a[@class=&quot;x_btn x_btn-small&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[3]/div[2]/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mulai')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bergabung'])[4]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Hacktivate Teknologi Indonesia. All Rights Reserved.'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balas'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDNAb3V0bG9vay5jb20iLCJpYXQiOjE1Njk1NjY5MTQsImV4cCI6MTU3MjE1ODkxNH0.V2TQFve5styB92OPXuFlRJov0IH1ED-O5Z2NOvqPj68&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting03@outlook.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
   </webElementXpaths>
</WebElementEntity>
