<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_devteamkodeid</name>
   <tag></tag>
   <elementGuidId>0d41d607-7363-4cb1-abc5-73db962e037f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail-app-component']/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/ul/li[3]/a/div/div[3]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>devteam@kode.id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail-app-component&quot;)/div[@class=&quot;W_6D6F D_F&quot;]/div[@class=&quot;D_F ab_FT em_N ek_BB&quot;]/div[@class=&quot;D_F H_6D6F ab_FT em_N M_0 p_R&quot;]/div[@class=&quot;W_6D6F H_6D6F cZ1RN91d_GG p_a o_h&quot;]/div[@class=&quot;W_6D6F H_6D6F&quot;]/div[@class=&quot;H_6D6F W_6D6F&quot;]/div[@class=&quot;p_R iy_h iz_A H_6D6F W_6D6F X_6Fd5 N_6Fd5 k_w&quot;]/div[@class=&quot;hd_n P_0 M_0 p_R&quot;]/ul[@class=&quot;hd_n P_0 M_0 p_R&quot;]/li[@class=&quot;p_a T_0 L_0 R_0&quot;]/a[@class=&quot;D_F r_P ab_C H_6TV4 bn_dBP bm_FJ bj_ajP6C p_R A_6EqO i_6FIA o_h X_eo6 h_Z1H3PfF ir3_Z1FS2Mn it3_689y I4_1YEmYj C_ZnIF8Y I3_ZFyHXD I_iJ8JF message-list-item&quot;]/div[@class=&quot;D_F o_h ab_C H_6D6F a_3vhr3 em_qk ej_0 p_R&quot;]/div[@class=&quot;D_F o_h G_e em_N&quot;]/span[@class=&quot;o_h G_e J_x em_N&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail-app-component']/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/ul/li[3]/a/div/div[3]/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan Harga Jual Terbaik Mobil Anda Sekarang.'])[1]/following::span[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IKLAN'])[1]/following::span[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Undangan bergabung ke KODE dari PT PALUGADA'])[1]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='devteam@kode.id'])[2]/preceding::span[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/span/span</value>
   </webElementXpaths>
</WebElementEntity>
