<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai</name>
   <tag></tag>
   <elementGuidId>3834c7a7-378c-4b05-9902-561fc48cede0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':9o']/div/div[2]/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Mulai' or . = 'Mulai')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDZAZ21haWwuY29tIiwiaWF0IjoxNTcwMTU5OTY3LCJleHAiOjE1NzAxNjAxNDd9.nAYnz2pB-YbbaTuVU2Qy3ZrM0JwJypXSrLmbZ2bTmg4&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting06@gmail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://ptolemy.kode.id/company/pt-palugada/verification?token%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDZAZ21haWwuY29tIiwiaWF0IjoxNTcwMTU5OTY3LCJleHAiOjE1NzAxNjAxNDd9.nAYnz2pB-YbbaTuVU2Qy3ZrM0JwJypXSrLmbZ2bTmg4%26companyId%3Ddd4c8941-0eab-43f9-a46f-6006685a7efa%26companyName%3DPT%2520PALUGADA%26userEmail%3Dkodetesting06@gmail.com&amp;source=gmail&amp;ust=1570246472570000&amp;usg=AFQjCNESn07YPKXXgeuMpESVKaBaQnAxgw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:9o&quot;)/div[@class=&quot;HOEnZb&quot;]/div[@class=&quot;im&quot;]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/table[2]/tbody[1]/tr[3]/td[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':9o']/div/div[2]/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Mulai')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kodetesting06@gmail.com'])[4]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important mainly because you often read messages with this label.'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Hacktivate Teknologi Indonesia. All Rights Reserved.'])[2]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ptolemy.kode.id/company/pt-palugada/verification?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkZDRjODk0MS0wZWFiLTQzZjktYTQ2Zi02MDA2Njg1YTdlZmEiLCJlbWFpbCI6ImtvZGV0ZXN0aW5nMDZAZ21haWwuY29tIiwiaWF0IjoxNTcwMTU5OTY3LCJleHAiOjE1NzAxNjAxNDd9.nAYnz2pB-YbbaTuVU2Qy3ZrM0JwJypXSrLmbZ2bTmg4&amp;companyId=dd4c8941-0eab-43f9-a46f-6006685a7efa&amp;companyName=PT%20PALUGADA&amp;userEmail=kodetesting06@gmail.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[2]/div/table/tbody/tr/td[2]/table[2]/tbody/tr[3]/td/a</value>
   </webElementXpaths>
</WebElementEntity>
